// Author: Brijesh Dave <https://github.com/brijeshdave>
// Renders the environment reference in /docs from the Zod env schema. Generated
// rather than written, so a new variable cannot be added without documenting it.
import { z } from "zod";

import { envSchema } from "@/core/env.js";

export interface EnvVarDoc {
  name: string;
  required: boolean;
  /** Rendered default, or null when the variable has none. */
  defaultValue: string | null;
  description: string;
}

/**
 * zod 4 keeps a schema's shape under `_zod.def` and names it `type: "default"`
 * rather than `typeName: "ZodDefault"`. Reading internals is the only way to ask
 * a schema "do you have a default", which is also why a zod major lands here.
 */
interface ZodInternals {
  type?: string;
  innerType?: z.ZodTypeAny;
  defaultValue?: unknown;
}

function internals(schema: z.ZodTypeAny): ZodInternals {
  return ((schema as unknown as { _zod?: { def?: ZodInternals } })._zod?.def ?? {}) as ZodInternals;
}

/** Strip `.default()` / `.optional()` to reach the described type. */
function unwrap(schema: z.ZodTypeAny): z.ZodTypeAny {
  let current = schema;
  for (;;) {
    const def = internals(current);
    if (def.innerType && ["default", "prefault", "optional", "nullable"].includes(def.type ?? "")) {
      current = def.innerType;
    } else {
      return current;
    }
  }
}

function describe(schema: z.ZodTypeAny): string {
  // `.describe()` may sit on the wrapper or on the inner type.
  return schema.description ?? unwrap(schema).description ?? "";
}

export function envVarDocs(): EnvVarDoc[] {
  const shape = envSchema.shape as Record<string, z.ZodTypeAny>;

  return Object.entries(shape).map(([name, schema]) => {
    const def = internals(schema);
    const hasDefault = def.type === "default" || def.type === "prefault";
    const isOptional = def.type === "optional";

    return {
      name,
      // A variable with a default never needs to be set; one without does.
      required: !hasDefault && !isOptional,
      // zod 4 stores the value itself; zod 3 stored a thunk that produced it.
      defaultValue: hasDefault ? String(def.defaultValue) : null,
      description: describe(schema),
    };
  });
}

/**
 * Escape a value for a markdown table cell.
 *
 * Backslashes first, then pipes — the other order is the classic incomplete
 * escape: a value ending in a backslash would have its own escape character
 * escaped by the pipe rule, and the pipe would break out of the cell. A newline
 * ends the row outright, so it becomes a space.
 *
 * Nothing untrusted reaches this today: the input is our own environment schema,
 * written in this repository and rendered at build time. It is correct anyway,
 * because "the input is trusted" is a property of today's callers rather than of
 * this function.
 */
function cell(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/[\r\n]+/g, " ");
}

export function renderEnvReference(): string {
  const rows = envVarDocs().map((entry) => {
    const requirement = entry.required ? "**yes**" : "no";
    const fallback =
      entry.defaultValue === null
        ? entry.required
          ? "—"
          : "_unset_"
        : `\`${cell(entry.defaultValue)}\``;
    return `| \`${entry.name}\` | ${requirement} | ${fallback} | ${cell(entry.description)} |`;
  });

  return [
    "<!-- Generated by `pnpm docs:env`. Edit apps/api/src/core/env.ts, not this file. -->",
    "",
    "# Environment reference",
    "",
    "Every variable the API reads, taken from its validation schema. The API refuses",
    "to start when a required variable is missing or malformed.",
    "",
    "| Variable | Required | Default | Description |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}
